baseURL = "https://engelsystem.de/doc/"
languageCode = "en-us"
title = "Engelsystem documentation"
theme = "learn"

[params]
themeVariant = "blue"
editURL = "https://github.com/engelsystem/engelsystem-doc/tree/main/content/"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true
